In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4]])

In [3]:
B = np.array([[3,4],[4,5]])

In [5]:
A+B

array([[4, 6],
       [7, 9]])

In [6]:
A.dot(B)

array([[11, 14],
       [25, 32]])

In [7]:
A*B

array([[ 3,  8],
       [12, 20]])

In [9]:
A.T

array([[1, 3],
       [2, 4]])

In [10]:
A[1,]

array([3, 4])

In [11]:
A[1]

array([3, 4])

In [13]:
A[:,1]

array([2, 4])