In [1]:
import numpy as np

In [2]:
from numpy.linalg import eig

In [3]:
A1 = np.array([[4, -2],
                   [1, 1]]);

In [5]:
eigenvalues1, eigenvectors1 = eig(A1);
print(eigenvalues1)
print(eigenvectors1)
print()


[3. 2.]
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]



In [7]:
A2 = np.array([[0, 1],
               [1, 0]]);
eigenvalues2, eigenvectors2 = eig(A2);
print(eigenvalues2)
print(eigenvectors2)
print()


[ 1. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]



In [9]:
A3 = np.array([[0, -1],
               [1, 0]]);
eigenvalues3, eigenvectors3 = eig(A3);
print(eigenvalues3)
print(eigenvectors3)
print()


[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]



In [10]:
    A4 = np.array([[1, 0],
                   [0, 1]]);
    eigenvalues4, eigenvectors4 = eig(A4);
    print(eigenvalues4)
    print(eigenvectors4)
    print()

[1. 1.]
[[1. 0.]
 [0. 1.]]



In [11]:
    A5 = np.array([[3, 1],
                   [0, 3]]);
    eigenvalues5, eigenvectors5 = eig(A5);
    print(eigenvalues5)
    print(eigenvectors5)
    print()

[3. 3.]
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  6.66133815e-16]]

